os: linux
dist: trusty

language: python
python:
  - 2.7
  - 3.6
 
sudo: required

notifications:
  email: false
git:
  depth: 99999999

addons:
  hostname: drmaa.travis-ci.org
  hosts:
    - localhost
    - localhost.localdomain
    - drmaa.travis-ci.org
 
before_install:
  - travis/install_sge.sh
  - export SGE_ROOT=/var/lib/gridengine
  - export SGE_CELL=default
  - export DRMAA_LIBRARY_PATH=/usr/lib/libdrmaa.so.1.0
  - sudo apt-get update -qq
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update -q -y conda
  - conda info -a
  - conda install -y -q drmaa

script:
  - python assembly/test/test_parsers.py
  - python typing/test/test_parsers.py
  - python tree/test/test_parsers.py

